### ISSUE TITLE
Is there anyway to do tab completion in this plugin

### ISSUE THREAD

**Issue by lord-shaz** [jtpio/jupyterlab-python-file#13]
This is my first time I'm trying to use jupyter lab to create .py file, and I'm sure that I've followed the exact instruction of installation,
however I'm not able to do tab completion. I'm not sure if there any way to do this, could you please help in this.

**Comment by jtpio** [comment]
@ShehzadaAlam to enable auto completion the file would have to be backed by a kernel.

That means creating a new console from the file:

![completion](https://user-images.githubusercontent.com/591645/86574397-10f8ac00-bf76-11ea-9187-7d643981d719.gif)

This should also apply to other languages other than Python.

**Comment by lord-shaz** [comment]
Yes its working, Thanks @jtpio

**Comment by jtpio** [comment]
Great! Closing as answered.
