### ISSUE TITLE
does this plugin allow path completion in python files?

### ISSUE THREAD

**Issue by whtns** [jtpio/jupyterlab-python-file#17]
path completion seems to work in the console. I'm new to the jupyter ecosystem. Path completion doesn't seem to work for me in notebooks either. Maybe this isn't available outside a console?

**Comment by jtpio** [comment]
Thanks @whtns.

This plugin only adds a convenient way to create a Python file to JupyterLab but doesn't change anything w.r.t the completion.

Maybe you have a screencast or screenshot that would give a bit more details?

Also it sounds like the issue could be moved to https://github.com/jupyterlab/jupyterlab instead. Alternatively you can also open a new topic on the Jupyter Discoure: discourse.jupyter.org/

**Comment by jtpio** [comment]
Closing as answered.

Thanks @whtns and feel free to open a new issue if you have more questions.
