### ISSUE TITLE
feature: code folding for python code (def, class, etc) 

### ISSUE THREAD

**Issue by ArcticSnow** [jtpio/jupyterlab-python-file#4]
Thanks for this great extension. This is not an issue but rather a feature idea.

Is there a way to obtain code folding for Python file, liek folding code blocks of one indentation level? Is that something that would depend on this extension, or would that be at another place in Jupyter lab?

**Comment by jtpio** [comment]
Thanks @ArcticSnow for filing the issue.

This is indeed more related to JupyterLab itself and its code editor.

There is an option in the settings to enable code folding that should work with any file (not only Python):

![code-folding](https://user-images.githubusercontent.com/591645/66575359-13a8ab00-eb76-11e9-958d-75250e1aa762.gif)

Hope this helps!

**Comment by ArcticSnow** [comment]
Thanks a lot @jtpio ! This works perfect
